<<<<<<< HEAD
use crate::foundations::{func, Str};

/// ダミーテキストの作成。
///
/// この関数は与えられた単語数だけラテン語風のダミーテキストである _Lorem Ipsum_ を生成します。
/// この関数で生成される単語の並びはランダムに選ばれますが、生成のたびに同じものになります。
/// 通常のダミーテキストと同様に、意味のないテキストです。
/// レイアウトを試すプレースホルダーとして使用してください。
///
/// # 例
=======
use crate::foundations::{Str, func};

/// Creates blind text.
///
/// This function yields a Latin-like _Lorem Ipsum_ blind text with the given
/// number of words. The sequence of words generated by the function is always
/// the same but randomly chosen. As usual for blind texts, it does not make any
/// sense. Use it as a placeholder to try layouts.
///
/// # Example
>>>>>>> dd1e6e94f73db6a257a5ac34a6320e00410a2534
/// ```example
/// = Blind Text
/// #lorem(30)
///
/// = More Blind Text
/// #lorem(15)
/// ```
#[func(keywords = ["Blind Text"])]
pub fn lorem(
<<<<<<< HEAD
    /// ダミーテキストの単語数。
=======
    /// The length of the blind text in words.
>>>>>>> dd1e6e94f73db6a257a5ac34a6320e00410a2534
    words: usize,
) -> Str {
    lipsum::lipsum(words).replace("--", "–").into()
}
